import type { TrainingPlan, Phase, Segment } from './training-plan-types'
import { AUDIENCE_LEVEL_LABELS } from './training-plan-types'

// ─── Markdown Export ──────────────────────────────────────────────────────────

function segmentToMarkdown(seg: Segment): string {
  const lines: string[] = []
  lines.push(`### ${seg.title} (${seg.timeMinutes} min)`)
  lines.push(`*Type: ${seg.type.replace(/_/g, ' ')}*`)
  if (seg.isPersonalized) lines.push('*✨ Personalized from workflow*')
  lines.push('')
  lines.push('🎤 **Script:**')
  lines.push('')
  // Indent each line of script as a blockquote
  seg.trainerScript.split('\n').forEach(line => {
    lines.push(`> ${line}`)
  })
  lines.push('')
  lines.push('📋 **Trainer Notes:**')
  lines.push('')
  seg.trainerNotes.split('\n').forEach(line => {
    lines.push(`> ${line}`)
  })
  if (seg.materials && seg.materials.length > 0) {
    lines.push('')
    lines.push('**Materials:**')
    seg.materials.forEach(m => lines.push(`- ${m}`))
  }
  return lines.join('\n')
}

function phaseToMarkdown(phase: Phase): string {
  const lines: string[] = []
  lines.push(`## Phase: ${phase.name} (${phase.timeMinutes} min)`)
  lines.push(`*Goal: ${phase.goal}*`)
  lines.push('')
  lines.push('---')
  lines.push('')
  phase.segments.forEach(seg => {
    lines.push(segmentToMarkdown(seg))
    lines.push('')
    lines.push('---')
    lines.push('')
  })
  return lines.join('\n')
}

export function planToMarkdown(plan: TrainingPlan): string {
  const { metadata, phases, trimmedModules } = plan
  const levelLabel = AUDIENCE_LEVEL_LABELS[metadata.audienceLevel]
  const dateFormatted = metadata.date
    ? new Date(metadata.date + 'T00:00:00').toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      })
    : 'TBD'

  const lines: string[] = []
  lines.push(`# Training Plan: ${metadata.client}`)
  lines.push('')
  lines.push(
    `**Trainer:** ${metadata.trainer} | **Date:** ${dateFormatted} | **Duration:** ${metadata.duration} minutes | **Audience:** ${levelLabel}`
  )
  lines.push('')
  lines.push(`**Modules Covered:** ${metadata.modules.join(', ')}`)
  lines.push('')

  if (trimmedModules && trimmedModules.length > 0) {
    lines.push(
      `> ⚠️ **Note:** The following modules were removed to fit within the ${metadata.duration}-minute session: ${trimmedModules.join(', ')}`
    )
    lines.push('')
  }

  lines.push('---')
  lines.push('')

  phases.forEach(phase => {
    lines.push(phaseToMarkdown(phase))
  })

  lines.push('---')
  lines.push('*Generated by SE Automator — Training Plan Generator*')

  return lines.join('\n')
}

export async function copyPlanAsMarkdown(plan: TrainingPlan): Promise<void> {
  const md = planToMarkdown(plan)
  await navigator.clipboard.writeText(md)
}

// ─── HTML Export ──────────────────────────────────────────────────────────────

const PHASE_COLORS: Record<string, { border: string; bg: string; text: string }> = {
  Connect: { border: '#3B82F6', bg: '#EFF6FF', text: '#1D4ED8' },
  Explore: { border: '#22C55E', bg: '#F0FDF4', text: '#15803D' },
  Apply: { border: '#F97316', bg: '#FFF7ED', text: '#C2410C' },
  Reflect: { border: '#8B5CF6', bg: '#F5F3FF', text: '#6D28D9' },
}

const TYPE_COLORS: Record<string, string> = {
  icebreaker: '#0EA5E9',
  lecture: '#6B7280',
  demo: '#0D9488',
  guided_exercise: '#16A34A',
  scenario: '#EA580C',
  knowledge_check: '#CA8A04',
  debrief: '#9333EA',
  handoff: '#0F766E',
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function markdownToHtml(md: string): string {
  // Very lightweight markdown → HTML for the export
  return md
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/^#{3}\s+(.+)$/gm, '<h4>$1</h4>')
    .replace(/^#{2}\s+(.+)$/gm, '<h3>$1</h3>')
    .replace(/^#{1}\s+(.+)$/gm, '<h2>$1</h2>')
    .replace(/^---$/gm, '<hr>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.+<\/li>\n?)+/g, (match) => `<ul>${match}</ul>`)
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank">$1</a>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br>')
}

function segmentToHtml(seg: Segment): string {
  const typeColor = TYPE_COLORS[seg.type] || '#6B7280'
  const typeLabel = seg.type.replace(/_/g, ' ').toUpperCase()
  const scriptHtml = markdownToHtml(escapeHtml(seg.trainerScript).replace(/&lt;br&gt;/g, '<br>'))
  const notesHtml = markdownToHtml(escapeHtml(seg.trainerNotes).replace(/&lt;br&gt;/g, '<br>'))

  return `
    <div class="segment">
      <div class="segment-header">
        <div class="segment-title-row">
          <span class="segment-title">${escapeHtml(seg.title)}</span>
          ${seg.isPersonalized ? '<span class="personalized-badge">✨ Personalized</span>' : ''}
          <span class="type-badge" style="background:${typeColor}20;color:${typeColor};border:1px solid ${typeColor}40">${typeLabel}</span>
          <span class="time-chip">${seg.timeMinutes} min</span>
        </div>
      </div>
      <div class="script-block">
        <div class="script-label">🎤 Say this:</div>
        <div class="script-content"><p>${scriptHtml}</p></div>
      </div>
      <div class="notes-block">
        <div class="notes-label">📋 Facilitator tip:</div>
        <div class="notes-content"><p>${notesHtml}</p></div>
      </div>
      ${
        seg.materials && seg.materials.length > 0
          ? `<div class="materials">
              <strong>Materials:</strong>
              <ul>${seg.materials.map(m => `<li>${escapeHtml(m)}</li>`).join('')}</ul>
             </div>`
          : ''
      }
    </div>
  `
}

function phaseToHtml(phase: Phase, idx: number): string {
  const colors = PHASE_COLORS[phase.name] || PHASE_COLORS['Connect']
  return `
    <section class="phase" id="phase-${idx + 1}" style="border-left:4px solid ${colors.border}">
      <div class="phase-header" style="background:${colors.bg}">
        <div class="phase-title" style="color:${colors.text}">Phase ${idx + 1}: ${phase.name}</div>
        <div class="phase-meta">
          <span class="phase-time">⏱ ${phase.timeMinutes} min</span>
          <span class="phase-goal">${escapeHtml(phase.goal)}</span>
        </div>
      </div>
      <div class="phase-body">
        ${phase.segments.map(segmentToHtml).join('')}
      </div>
    </section>
  `
}

export function downloadPlanAsHtml(plan: TrainingPlan): void {
  const { metadata, phases, trimmedModules } = plan
  const levelLabel = AUDIENCE_LEVEL_LABELS[metadata.audienceLevel]
  const dateFormatted = metadata.date
    ? new Date(metadata.date + 'T00:00:00').toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      })
    : 'TBD'

  const toc = phases
    .map((p, i) => `<li><a href="#phase-${i + 1}">Phase ${i + 1}: ${p.name} (${p.timeMinutes} min)</a></li>`)
    .join('\n')

  const phasesHtml = phases.map((p, i) => phaseToHtml(p, i)).join('\n')

  const trimmedWarning = trimmedModules && trimmedModules.length > 0
    ? `<div class="warning">⚠️ <strong>Note:</strong> The following modules were removed to fit within the ${metadata.duration}-minute session: ${escapeHtml(trimmedModules.join(', '))}</div>`
    : ''

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Training Plan: ${escapeHtml(metadata.client)}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      font-size: 14px;
      line-height: 1.6;
      color: #1f2937;
      background: #f9fafb;
      padding: 2rem;
    }
    .container { max-width: 900px; margin: 0 auto; }
    .cover {
      background: white;
      border-radius: 12px;
      padding: 2rem;
      margin-bottom: 2rem;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    .cover h1 { font-size: 1.75rem; font-weight: 700; color: #111827; margin-bottom: 0.5rem; }
    .cover .meta { color: #6b7280; margin-bottom: 0.75rem; font-size: 0.875rem; }
    .cover .modules { color: #374151; font-size: 0.875rem; }
    .toc {
      background: white;
      border-radius: 12px;
      padding: 1.5rem;
      margin-bottom: 2rem;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
    .toc h2 { font-size: 1rem; font-weight: 600; margin-bottom: 0.75rem; color: #374151; }
    .toc ul { padding-left: 1.5rem; }
    .toc li { margin-bottom: 0.25rem; }
    .toc a { color: #059669; text-decoration: none; }
    .toc a:hover { text-decoration: underline; }
    .warning {
      background: #fffbeb;
      border: 1px solid #fcd34d;
      border-radius: 8px;
      padding: 0.75rem 1rem;
      margin-bottom: 1.5rem;
      font-size: 0.875rem;
      color: #92400e;
    }
    .phase {
      background: white;
      border-radius: 12px;
      margin-bottom: 2rem;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
      overflow: hidden;
    }
    .phase-header {
      padding: 1.25rem 1.5rem;
      border-bottom: 1px solid rgba(0,0,0,0.06);
    }
    .phase-title { font-size: 1.125rem; font-weight: 700; margin-bottom: 0.25rem; }
    .phase-meta { display: flex; gap: 1rem; align-items: center; font-size: 0.8rem; color: #6b7280; }
    .phase-time { font-weight: 600; }
    .phase-body { padding: 1rem 1.5rem; }
    .segment {
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      padding: 1rem;
      margin-bottom: 1rem;
    }
    .segment-header { margin-bottom: 0.75rem; }
    .segment-title-row {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      flex-wrap: wrap;
    }
    .segment-title { font-weight: 600; font-size: 0.9375rem; color: #111827; }
    .type-badge {
      font-size: 0.6875rem;
      font-weight: 600;
      padding: 0.125rem 0.5rem;
      border-radius: 999px;
      letter-spacing: 0.04em;
    }
    .personalized-badge {
      font-size: 0.6875rem;
      font-weight: 600;
      padding: 0.125rem 0.5rem;
      border-radius: 999px;
      background: #d1fae5;
      color: #065f46;
      border: 1px solid #6ee7b7;
    }
    .time-chip {
      margin-left: auto;
      font-size: 0.75rem;
      font-weight: 500;
      color: #6b7280;
      background: #f3f4f6;
      padding: 0.125rem 0.5rem;
      border-radius: 4px;
    }
    .script-block {
      background: #eff6ff;
      border-radius: 6px;
      padding: 0.875rem;
      margin-bottom: 0.75rem;
    }
    .script-label {
      font-size: 0.75rem;
      font-weight: 600;
      color: #1d4ed8;
      margin-bottom: 0.5rem;
    }
    .script-content { color: #1e3a5f; font-size: 0.875rem; line-height: 1.7; }
    .script-content p { margin-bottom: 0.5rem; }
    .script-content p:last-child { margin-bottom: 0; }
    .script-content strong { font-weight: 600; }
    .notes-block {
      background: #fffbeb;
      border-radius: 6px;
      padding: 0.875rem;
      margin-bottom: 0.5rem;
    }
    .notes-label {
      font-size: 0.75rem;
      font-weight: 600;
      color: #92400e;
      margin-bottom: 0.5rem;
    }
    .notes-content { color: #78350f; font-size: 0.875rem; line-height: 1.7; }
    .notes-content p { margin-bottom: 0.5rem; }
    .notes-content p:last-child { margin-bottom: 0; }
    .materials { font-size: 0.8125rem; color: #374151; margin-top: 0.5rem; }
    .materials ul { padding-left: 1.25rem; margin-top: 0.25rem; }
    .materials li { margin-bottom: 0.125rem; }
    .footer {
      text-align: center;
      color: #9ca3af;
      font-size: 0.75rem;
      margin-top: 2rem;
      padding-top: 1.5rem;
      border-top: 1px solid #e5e7eb;
    }
    @media print {
      body { background: white; padding: 0; }
      .phase { page-break-before: always; box-shadow: none; border: 1px solid #e5e7eb; }
      .phase:first-of-type { page-break-before: avoid; }
      .toc { page-break-after: always; }
      a { color: inherit; text-decoration: none; }
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="cover">
      <h1>Training Plan: ${escapeHtml(metadata.client)}</h1>
      <p class="meta">
        <strong>Trainer:</strong> ${escapeHtml(metadata.trainer)} &nbsp;|&nbsp;
        <strong>Date:</strong> ${escapeHtml(dateFormatted)} &nbsp;|&nbsp;
        <strong>Duration:</strong> ${metadata.duration} minutes &nbsp;|&nbsp;
        <strong>Audience:</strong> ${escapeHtml(levelLabel)}
      </p>
      <p class="modules"><strong>Modules Covered:</strong> ${escapeHtml(metadata.modules.join(', '))}</p>
    </div>

    <div class="toc">
      <h2>Table of Contents</h2>
      <ul>${toc}</ul>
    </div>

    ${trimmedWarning}

    ${phasesHtml}

    <div class="footer">Generated by SE Automator — Training Plan Generator</div>
  </div>
</body>
</html>`

  const blob = new Blob([html], { type: 'text/html;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `training-plan-${metadata.client.toLowerCase().replace(/\s+/g, '-')}-${metadata.date || 'undated'}.html`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function printPlan(): void {
  window.print()
}
