name: UATChecklist
options:
  bundleIdPrefix: com.talkpush
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"

targets:
  UATChecklist:
    type: application
    platform: iOS
    sources:
      - UATChecklist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.talkpush.uat-checklist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: UATChecklist/Resources/Info.plist
        DEVELOPMENT_TEAM: ""
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - package: Supabase
        product: Supabase
